server:
  port: 8207
spring:
  application:
    name: nacos-user-service
  cloud:
    nacos:
      discovery:
#        server-addr: 10.203.20.93:8848
        server-addr: 192.168.0.106:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'