server:
  port: 8308
spring:
  application:
    name: nacos-ribbon-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.203.20.93:8848
service-url:
  nacos-user-service: http://nacos-user-service
